// avoids typescript errors on image imports
declare module "*.svg"
declare module "*.svg?inline"
declare module "*.jpg"
declare module "*.jpg?glowsite"
declare module "*.png?glowsite"
declare module "*.jpg?glowsite&w="
declare module "*.png?glowsite&w="
declare module "*.png"
declare module "typedoc:*"
declare module "react-docgen:*"
declare module "*.mjs"
