name: Preview and downloads frequent build and deploy
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install packages
        run: pnpm install

      - name: Build site
        run: pnpm run build:www
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Deploy site
        run: ./deploy-site.sh www preview.glowbuzzer.com E284GBH6OG76DV

  deploy-downloads:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install packages
        run: pnpm install

      - name: Build site
        run: pnpm run build:downloads

      - name: Deploy site
        run: ./deploy-site.sh downloads downloads.glowbuzzer.com E36QR0RH2CR6EK
