name: Preview and downloads frequent build and deploy
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install packages
        run: pnpm install

      - uses: browser-actions/setup-chrome@v1

      - name: Symlink Chrome so Mermaid can find it
        run: |
          echo $(which chrome)
          ls -l /usr/bin/google-chrome
          google-chrome --version
          chrome --version

      - name: Build site
        run: pnpm run build:www
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          VITE_GLOWBUZZER_VERSION: preview

      - name: Generate index
        run: node post-process-site.mjs preview.glowbuzzer.com

      - name: Deploy site
        run: ./deploy-site.sh www preview.glowbuzzer.com E284GBH6OG76DV

  deploy-downloads:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install packages
        run: pnpm install

      - name: Build site
        run: pnpm run build:downloads

      - name: Deploy site
        run: ./deploy-site.sh downloads downloads.glowbuzzer.com E36QR0RH2CR6EK
