name: glowsite-release

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: glowsite
          changelog-types: '[ { "type": "feat", "section": "Feature" }, { "type": "fix", "section": "Bug Fix" }, { "type": "docs", "section": "Documentation" }, { "type": "enh", "section": "Enhancement" }, { "type": "chore", "section": "Chore" } ]'

  publish-www:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install packages
        run: pnpm install

      - name: Build site
        run: pnpm run build:www
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          VITE_GLOWBUZZER_VERSION: ${{ needs.release-please.outputs.version }}

#
#      - name: Install Chrome
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y wget gnupg
#          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
#          sudo apt-get update
#          sudo apt-get install -y google-chrome-stable
#
#      - name: Generate index
#        run: node post-process-site.mjs www.glowbuzzer.com

      - name: Deploy site
        run: ./deploy-site.sh www www.glowbuzzer.com EOLCC9H61HP6F

