name: www.glowbuzzer.com RELEASE build and deploy
on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v1

            -   uses: actions/setup-node@v1
                with:
                    node-version: "14.x"

            -   uses: pnpm/action-setup@v2.0.1
                with:
                    version: 6.13.0

            -   name: Install packages
                run: pnpm install # --no-optional
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   name: Build site
                run: export VITE_GLOWBUZZER_VERSION=${GITHUB_REF#refs/tags/} && pnpm run build:www

            -   name: Deploy site
                run: ./deploy-site.sh www www.glowbuzzer.com EOLCC9H61HP6F
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    BUILD_NUM: 1.${{ github.run_number }}
